import autogen
from PyPDF2 import PdfReader
import csv
import re
import io
from docx import Document
import os
import logging
from typing import List, Dict, Any

# Configuration
LLM_CONFIG = {
    "cache_seed": 82,
    "temperature": 0,
    "config_list": [{
        'model': 'gpt-4o',
        'api_type': 'azure',
        'base_url': " ",
        'api_version': '2024-03-01-preview',
        'api_key': os.environ.get('AZURE_API_KEY', "")
    }],
    "timeout": 180
}

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Agent Initialization
def create_agent(name: str, system_message: str) -> autogen.AssistantAgent:
    return autogen.AssistantAgent(
        name=name,
        system_message=system_message,
        llm_config=LLM_CONFIG,
        max_consecutive_auto_reply=1
    )

BRDAnalyst = create_agent(
    "BRDAnalyst",
    """You are an experienced business analyst tasked with analyzing a Business Requirements Document (BRD) to extract relevant requirements for software application testing.

1. Analyze the BRD's logic, delineate the scope, including in-scope and out-of-scope items, and align them with business goals.
2. Understand the full context of the project. Identify any platform-specific requirements or constraints.
3. Carefully analyze the user input to understand the context and requirements. Identify any additional specifications or details that could enhance test case generation.
4. Follow the instructions provided by the user. Extract the relevant links or URLs from the BRD as well.
5. Compile and present the extracted information that will aid TestCaseGenerator in developing comprehensive test cases.
6. Extract ALL URLs and relevant contents from the given context, even if they seem tangentially related.
7. Review the BRD content and identify requirements related to software functionality, performance, security, and user experience.
8. Present the extracted requirements in a clear, structured format to provide the TestCaseGenerator with a comprehensive set of testing requirements.
9. For each requirement, feature, or any relevant information, provide ALL related URLs or links that were extracted, try to understand the URLs and BRD information.
10. Avoid including details not directly related to software testing, and do not create test cases. Your role is to provide the TestCaseGenerator with the relevant information for them to develop the necessary test cases.
"""
)

TestCaseGenerator = create_agent(
    "TestCaseGenerator",
    """You are a Quality Assurance engineer who creates test cases.
Generate comprehensive test cases based on the given business requirements gained from BRDAnalyst. Analyze and try to understand each line of requirements carefully.
Include test scenarios, test case IDs, steps, expected results, related URLs (which are related to that particular test scenario) and conditions from the BRDAnalyst.
Cover functional test cases including positive, negative, and edge cases. Check the relevant matching URLs or links for the particular test case and add it for the respective test cases. Only the matching URLs should be passed.
Try to add advanced and detailed test cases and add all the steps.

Format your response EXACTLY as follows:
Test Scenario: [Scenario Name]
Test Case ID: [ID]
Step 1: [Test Case Step 1]
Expected Result: [Expected Result for Step 1]
Step 2: [Test Case Step 2]
Expected Result: [Expected Result for Step 2]
.......................................
.......................................
(continue with as many steps as needed)
URLs: [related URLs]
Conditions: [Conditions if any]

(Repeat this structure for each test case and scenario)

Pass the test scenarios and test cases to TestCaseReviewer for refinement and review."""
)

TestCaseReviewer = create_agent(
    "TestCaseReviewer",
    """You are a Quality Assurance manager who reviews and refines test cases. Your task is to:
1. Review and refine the test scenarios and test cases generated by TestCaseGenerator.
2. Ensure all aspects of the requirements are covered, including platform-specific or role-based access control test cases, if mentioned in the requirements.
3. Add more scenarios and edge cases if needed. Try to add advanced and detailed test cases and add all the steps.
4. Ensure each test case has an appropriate number of steps (at least 3, but as many as needed).
5. Break down complex and lengthy test cases if necessary, for example, break 8-step test cases into 2 with 4 steps each. Avoid redundant steps in test cases.
6. Add test cases for error handling, performance, and security if not covered.
7. Review the URLs associated with each test case. Add any additional relevant URLs that may have been missed, based on the information from BRDAnalyst.
8. Be inclusive with URL associations - if a link could potentially provide useful information or context for a test case, include it. Try to give the similar URL for same test scenarios.
9. If you find any URLs that seem completely unrelated or irrelevant, if you do not find any matching URLs or links for a particular test case do not add it, keep it blank.
10. Avoid redundant and duplicate test cases and scenarios. For every test case, there should be a test scenario.

Strict rule:
- Maintain EXACTLY the same format as provided in the TestCaseGenerator."""
)

HumanProxy = autogen.UserProxyAgent(
    name="HumanProxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=1,
    code_execution_config={"work_dir": "coding", "use_docker": False} )

# Set up the group chat
GroupChat = autogen.GroupChat(
    agents=[HumanProxy, BRDAnalyst, TestCaseGenerator, TestCaseReviewer],
    messages=[],
    max_round=5,
    max_retries_for_selecting_speaker=2,
    select_speaker_auto_verbose=False,
    send_introductions=False,
    allow_repeat_speaker=False, )

ChatManager = autogen.GroupChatManager(groupchat=GroupChat, llm_config=LLM_CONFIG)


def extract_test_cases(content: str) -> Dict[str, List[Dict[str, Any]]]:
    scenarios = {}
    for scenario_content in re.split(r'#* Test Scenario:', content)[1:]:
        lines = scenario_content.strip().split('\n')
        scenario_name = lines[0].strip()
        for case_part in re.split(r'Test Case ID:', '\n'.join(lines[1:]))[1:]:
            case_lines = case_part.strip().split('\n')
            urls = [url for _, url in re.findall(r'\[(.*?)\]\((.*?)\)', case_part)]
            steps = re.findall(r'\*\*Step \d+:\*\* (.*?)(?=\*\*Step \d+:\*\*|\Z)', case_part, re.DOTALL)
            expected_results = [re.search(r'Expected Result:\s*(.*)', step) for step in steps]
            expected_results = [result.group(1).strip() if result else '' for result in expected_results]
            condition = re.search(r'Conditions:\s*(.*)', case_part)
            scenarios.setdefault(scenario_name, []).append({
                'case_id': case_lines[0].strip(),
                'urls': urls,
                'steps': [step.strip().split('\n')[0] for step in steps],
                'expected_results': expected_results,
                'condition': condition.group(1).strip() if condition else ''
            })
    return scenarios

def generate_test_cases(file_content: str, file_url: str, url: str, content: str, text_content: str) -> str:
    message = f"""Here's the BRD content:

        {file_content} and {file_url}

        Here are the url and its content:
        {url}
        {content}

        Here is the user input:
        {text_content}

        Use BRDAnalyst to gain the information that are related to testing.
        Generate test cases based on the requirements using TestCaseGenerator and then use TestCaseReviewer to review and refine them.
        Ensure that the final output is EXACTLY in the format specified in the TestCaseGenerator's system message."""

    chat_result = HumanProxy.initiate_chat(ChatManager, message=message)
    
    scenarios = {}
    max_steps = max_urls = 0
    for message in GroupChat.messages:
        if message['name'] == 'TestCaseReviewer':
            extracted = extract_test_cases(message['content'])
            for scenario, cases in extracted.items():
                scenarios.setdefault(scenario, []).extend(cases)
                max_steps = max(max_steps, max(len(case['steps']) for case in cases))
                max_urls = max(max_urls, max(len(case['urls']) for case in cases))

    headers = ['Test Scenario', 'Test Case ID'] + sum([
        [f'Step {i+1}', f'Step {i+1} Expected Result'] for i in range(max_steps)
    ], []) + ['Conditions'] + [f'URL {i+1}' for i in range(max_urls)]

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(headers)

    for scenario, cases in scenarios.items():
        for case in cases:
            row = [scenario, case['case_id']]
            for step, expected in zip(case['steps'] + [''] * (max_steps - len(case['steps'])),
                                      case['expected_results'] + [''] * (max_steps - len(case['expected_results']))):
                row.extend([step, expected])
            row.extend([case['condition']] + case['urls'] + [''] * (max_urls - len(case['urls'])))
            writer.writerow(row)

    return output.getvalue()